from openpyxl import Workbook
from openpyxl.styles import *
from openpyxl.worksheet.table import Table, TableStyleInfo

# opening text file for reading

text_file = open("C:\\Users\\sakew\\PycharmProjects\\pythonProject\\ExcelAutomation\\employees.txt")

# Creating an empty list to store the records as a list of lists

records = []

# Setting the reading pointer at the beginning of the file

text_file.seek(0)

# Splitting each line in the file by the ";" delimiter and appending each list generated by readlines() to the new list, records

for record in text_file.readlines():
    records.append(record.rstrip("\n").split(";"))

# Creating a new workbook object, by initializing the Workbook() Class

workbook = Workbook()

# storing the path to a variable "file_path"

file_path = "C:\\Users\\sakew\\PycharmProjects\\pythonProject\\ExcelAutomation\\CompanyStaff.xlsx"

# Saving the workbook

workbook.save(file_path)

# Rename the default sheet to 'Employees'

sheet = workbook['Sheet']

sheet.title = 'Employees'

# Referencing the sheet

sheet = workbook['Employees']

# Populating the sheet with the rows from the text file
# The table header will be created from the first row in the text file.

for row in records:
    sheet.append(row)

# Creating a table inside the sheet

table = Table(displayName="Table", ref="A1:G11")

# Defining a style for the table.

style = TableStyleInfo(name="TableStyleMedium9", showRowStripes=True, showColumnStripes=True)

# Applying the style to the table

table.tableStyleInfo = style

# Adding the newly created table to the sheet

sheet.add_table(table)

# Defining the font

font = Font(color='FFFF0000', bold=True, italic=True)

# Applying the font to the cells with the salary condition

for cell_no in range(2, 12):
    if int(sheet['G%s' % (cell_no)].value) > 55000:
        sheet['G%s' % (cell_no)].font = font

# saving the workbook

workbook.save(file_path)

# closing the text file

text_file.close()

# closing the workbook

workbook.close()
