import psycopg2

# Opening the text file for reading the records

f = open("C:\\Users\\sakew\\PycharmProjects\\pythonProject\\DatabaseAutomationPostgreSQL\\employees2.txt")

# Create an empty list for storing the records as a list of lists.

records = []

# Splitting each line in the file by the "/ " delimiter and appending each list generated by readlines() to the new list, records

for i in f.readlines():
    records.append(i.split("/ "))

print(records)

# establishing the connection to the database.

try:
    connection = psycopg2.connect(database="staff", user="sakew", password="",
                                  host="127.0.0.1", port="5432")

except psycopg2.Error as err:
    print("An error was generated!")
else:
    print("Connection to the database was successful!")

# initializing the cursor

cursor = connection.cursor()

# iterating over the records list and each inner list, extracting the data associated with each column

try:
    for i in records:
        cursor.execute("insert into mystaff.employees (id,first_name,last_name,department,phone,address,salary) values (%s,%s,%s,%s,%s,%s,%s);",(i[0], i[1], i[2], i[3], i[4], i[5], i[6]))

except psycopg2.Error as err:
    print("An error has occurred while inserting the records!")
else:
    print("Records inserted successfully!")

# saving the changes to database
connection.commit()
# Closing the connection to the database
connection.close()
